apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All resources needed for the application package
resources:
  - redis/kubernetes.yml
  - backend-golang/kubernetes.yml
  - backend-spring/kubernetes.yml
  - frontend-nodejs/kubernetes.yml

# Merge an overlay file that modifies the number of replicas
patchesStrategicMerge:
  - kustom-overlay.yml

# Generate a translation config from literals
configMapGenerator:
  - name: translation-config
    literals:
      - greetingLabel=Hello

generatorOptions:
  disableNameSuffixHash: true
