apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All resources needed for the application package
resources:
  - redis/kubernetes.yml
  - backend-golang/kubernetes.yml
  - backend-spring/kubernetes.yml
  - frontend-nodejs/kubernetes.yml
