apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All resources needed for the application package
resources:
  - redis/kubernetes.yml
  - keycloak/kubernetes.yml
  - backend-golang/kubernetes.yml
  - backend-spring/kubernetes.yml
  - frontend-nodejs/kubernetes.yml

# Generate a translation config from literals
configMapGenerator:
  - name: translation-config
    literals:
      - greetingLabel=Hello
  - name: envoy-config-backend
    files:
      - backend-envoy/envoy.yml
  - name: envoy-config-frontend
    files:
      - frontend-envoy/envoy.yml
  - name: keycloak-realm
    files:
      - keycloak/simple-realm.json