kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-golang-pod
  template:
    metadata:
      labels:
        app: backend-golang-pod
    spec:
      volumes:
        - name: tls-volume
          secret:
            secretName: tls-secret
        - name: envoy-volume
          configMap:
            name: envoy-config-backend
      containers:
        - name: envoy-golang-container
          image: envoyproxy/envoy:v1.24.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tls-volume
              mountPath: "/etc/tls"
              readOnly: true
            - name: envoy-volume
              mountPath: "/etc/envoy"
              readOnly: true
          ports:
            - containerPort: 8443
              name: envoy-port
          args:
            - "-c"
            - "/etc/envoy/envoy.yml"
        - name: backend-golang-container
          image: mouton4711/hello_k8s_backend-golang
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: translation-config

---
kind: Service
apiVersion: v1
metadata:
  name: backend-golang
spec:
  type: ClusterIP
  selector:
    app: backend-golang-pod
  ports:
    - port: 443
      targetPort: envoy-port
