kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-golang
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-golang-pod
  template:
    metadata:
      labels:
        app: backend-golang-pod
    spec:
      volumes:
        - name: tls-volume
          secret:
            secretName: tls-secret
      containers:
        - name: sidecar-golang-container
          image: mouton4711/hello_k8s_backend-envoy
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tls-volume
              mountPath: "/etc/tls"
              readOnly: true
          ports:
            - containerPort: 8443
              name: sidecar-port
        - name: backend-golang-container
          image: mouton4711/hello_k8s_backend-golang
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: translation-config

---
kind: Service
apiVersion: v1
metadata:
  name: backend-golang
spec:
  type: ClusterIP
  selector:
    app: backend-golang-pod
  ports:
    - port: 443
      targetPort: sidecar-port
