kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-golang
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-golang-pod
  template:
    metadata:
      labels:
        app: backend-golang-pod
    spec:
      containers:
        - name: sidecar-golang-container
          image: mouton4711/kubernetes:envoy-sidecar
          ports:
            - containerPort: 8888
              name: sidecar-port
        - name: backend-golang-container
          image: mouton4711/kubernetes:backend-golang

---
kind: Service
apiVersion: v1
metadata:
  name: backend-golang
spec:
  type: ClusterIP
  selector:
    app: backend-golang-pod
  ports:
    - port: 80
      targetPort: sidecar-port
