kind: Deployment
apiVersion: apps/v1
metadata:
  name: backend-spring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-spring-pod
  template:
    metadata:
      labels:
        app: backend-spring-pod
    spec:
      containers:
        - name: sidecar-spring-container
          image: mouton4711/kubernetes:backend-envoy
          ports:
            - containerPort: 8888
              name: sidecar-port
        - name: backend-spring-container
          image: mouton4711/kubernetes:backend-spring

---
kind: Service
apiVersion: v1
metadata:
  name: backend-spring
spec:
  type: ClusterIP
  selector:
    app: backend-spring-pod
  ports:
    - port: 80
      targetPort: sidecar-port