kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nodejs-pod
  template:
    metadata:
      labels:
        app: frontend-nodejs-pod
    spec:
      containers:
        - name: sidecar-nodejs-container
          image: mouton4711/kubernetes:frontend-envoy
          ports:
            - containerPort: 8443
              name: sidecar-port
        - name: frontend-nodejs-container
          image: mouton4711/kubernetes:frontend-nodejs

---
kind: Service
apiVersion: v1
metadata:
  name: frontend-nodejs
spec:
  type: LoadBalancer
  selector:
    app: frontend-nodejs-pod
  ports:
    - port: 443
      targetPort: sidecar-port


