kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-nodejs-pod
  template:
    metadata:
      labels:
        app: frontend-nodejs-pod
    spec:
      volumes:
        - name: tls-volume
          secret:
            secretName: tls-secret
        - name: envoy-volume
          configMap:
            name: envoy-config-frontend
      containers:
        - name: envoy-nodejs-container
          image: envoyproxy/envoy:v1.24.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: tls-volume
              mountPath: "/etc/tls"
              readOnly: true
            - name: envoy-volume
              mountPath: "/etc/envoy"
              readOnly: true
          ports:
            - containerPort: 8443
              name: envoy-port
          args:
            - "-c"
            - "/etc/envoy/envoy.yml"
        - name: frontend-nodejs-container
          image: mouton4711/hello_k8s_frontend-nodejs
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: translation-config
          env:
            - name: BACKEND_HOSTS
              value: "localhost:7777/golang,localhost:7777/spring" # Routes of the egress Envoy proxy

---
kind: Service
apiVersion: v1
metadata:
  name: frontend-nodejs
spec:
  type: LoadBalancer
  selector:
    app: frontend-nodejs-pod
  ports:
    - port: 443
      targetPort: envoy-port


